# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: | 
        cd src 
        go build -o ./agent

    - name: Upload agent to r2
      id: upload-release-artifact
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.R2_NEW_TOKNE }}
        file: ./src/agent
        repo_name: Zzzjm1919/r2
